### ISSUE TITLE
Housekeeping questions

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/atomium#1]
Awesome to see this in Backdrop Contrib now! A few housekeeping kinds of questions for you @drupol:

1. Would it make sense to track version numbers with the parallel Drupal 7 version? e.g. if this is essentially the same functionality as 7.x-2.25, the Backdrop release could be 1.x-2.25.

2. Should the badges be updated?
![Screen Shot 2019-05-13 at 10 03 49 AM](https://user-images.githubusercontent.com/871421/57632093-6d289180-7566-11e9-92fc-683e948f3ba5.jpg)

**Comment by drupol** [comment]
Let's consider this `1.x-1.0` version as a pre-flight version of Atomium for Backdrop, I will definitely follow the same version number as in Drupal 7, I'm just waiting to have a bit of feedback around this very first release.
